var data = {
    "nodes":[
		{"id":"1","name":"Geographic knowledge extraction and semantic similarity in OpenStreetMap"},
		{"id":"2","name":"Discovering missing links in Wikipedia"},
		{"id":"3","name":"Astudy on similarity and relatedness using distributional andWordnet-based approaches"},
		{"id":"4","name":"Statistics in medicine: calculating confidence intervals for regression and correlation"},
		{"id":"5","name":"Applications of citation-based automatic classification"},
		{"id":"6","name":"LinkedGeoData: adding a spatial dimension to the web of data"},
		{"id":"7","name":"Semantically enriching VGI in support of implicit feedback analysis"},
		{"id":"8","name":"A survey of volunteered open geo-knowledge bases in the semantic web"},
		{"id":"9","name":"Graph structure in the web"},
		{"id":"10","name":"A spreading-activation theory of semantic processing"},
		{"id":"11","name":"A primer on meta-analysis of correlation coefficients: the relationship between patient-reported therapeutic alliance and adult attachment style as an illustration"},
		{"id":"12","name":"Ontological bridge building—using ontologies to merge spatial datasets"},
		{"id":"13","name":"Toward the semantic geospatial web"},
		{"id":"14","name":"An overview of FIPS 173  the spatial data transfer standard."},
		{"id":"15","name":"Meta-analysis of correlation coefficients: A monte carlo comparison of fixed- and random effects methods"},
		{"id":"16","name":"Content based similarity of geographic classes organized as partition hierarchies"},
		{"id":"17","name":"Towards ubiquitous cartography"},
		{"id":"18","name":"GeoWordNet: a resource for geo-spatial applications"},
		{"id":"19","name":"Citizens as sensors: the world of volunteered geography"},
		{"id":"20","name":"How good is volunteered geographical information? A comparative study of Open- StreetMap and ordnance survey datasets"},
		{"id":"21","name":"Web mapping 2"},
		{"id":"22","name":"OpenStreetMap: user-generated street maps"},
		{"id":"23","name":"The complex dynamics of collaborative tagging"},
		{"id":"24","name":"WiKi’mantics: interpreting ontologies with Wikipedia"},
		{"id":"25","name":"Methods of meta-analysis: correcting error and bias in research findings"},
		{"id":"26","name":"A study on the cognitive plausibility of SIM-DL similarity rankings for geographic feature types"},
		{"id":"27","name":"Algorithm"},
		{"id":"28","name":"The semantics of similarity in geographic information retrieval  implementation and application of the SIM-DL similarity server."},
		{"id":"29","name":"Semantic similarity measurement and geospatial applications"},
		{"id":"30","name":"SimRank: a measure of structural-context similarity"},
		{"id":"31","name":"What is the difference? A cognitive dissimilarity measure for information retrieval result sets"},
		{"id":"32","name":"Bibliographic coupling between scientific papers"},
		{"id":"33","name":"Geospatial semantics: why"},
		{"id":"34","name":"Fast single-pair SimRank computation"},
		{"id":"35","name":"A qualitative enquiry into OpenStreetMap making"},
		{"id":"36","name":"MatchSim: a novel similarity measure based on maximum neighborhood matching"},
		{"id":"37","name":"On efficient distance-based similarity search"},
		{"id":"38","name":"Accuracy estimate and optimization techniques for SimRank computation"},
		{"id":"39","name":"Ontologies are us: a unifiedmodel of social networks and semantics"},
		{"id":"40","name":"WordNet: a lexical database for English"},
		{"id":"41","name":"Contextual correlates of semantic similarity"},
		{"id":"42","name":"Ranking the linked data: the case of DBpedia"},
		{"id":"43","name":"Characteristics of heavily edited objects in OpenStreetMap"},
		{"id":"44","name":"Towards quality metrics forOpenStreetMap"},
		{"id":"45","name":"Analyzing the spatial-semantic interaction of points of interest in volunteered geographic information"},
		{"id":"46","name":"Wikipedia link structure and text mining for semantic relation extraction  Towards a huge scale globalweb ontology"},
		{"id":"47","name":"OpenStreetMap’s growth accelerates"},
		{"id":"48","name":"The computational Geowiki: what why and how"},
		{"id":"49","name":"Using information content to evaluate semantic similarity in a taxonomy"},
		{"id":"50","name":"Emergence of consensus and shared vocabularies in collaborative tagging systems"},
		{"id":"51","name":"Comparing geospatial entity classes: an asymmetric and contextdependent similarity measure"},
		{"id":"52","name":"Contextual correlates of synonymy"},
		{"id":"53","name":"Approaches to semantic similarity measurement for geo-spatial data: a survey"},
		{"id":"54","name":"On similarity measures for multimedia database applications"},
		{"id":"55","name":"Co-citation in the scientific literature: a new measure of the relationship between two documents"},
		{"id":"56","name":"Principles of semantic networks: explorations in the representation of knowledge"},
		{"id":"57","name":"The proof and measurement of association between two things"},
		{"id":"58","name":"The wikification of GIS and its consequences: or Angelina Jolie’s new tattoo and the future of GIS"},
		{"id":"59","name":"Semantic relatedness metric forWikipedia concepts based on link analysis and its application to word sense disambiguation"},
		{"id":"60","name":"Introduction to neogeography"},
		{"id":"61","name":"Beyond topical similarity: a structural similarity measure for retrieving highly similar documents"},
		{"id":"62","name":"Philosophical investigations"},
		{"id":"63","name":"P-Rank: a comprehensive structural similarity measure over information networks"},
        {"id":"64","name":"Dbpedia: A nucleus for a web of open data"},
        {"id":"65","name":"Triplify - lightweight linked data publication from relational databases"},
        {"id":"66","name":"An instance-based approach for matching export schemas of geographical database Web services"},
        {"id":"67","name":"Learning highly structured semantic repositories from relational databases"},
        {"id":"68","name":"COMA - A system for exible combination of schema matching approaches"},
        {"id":"69","name":"Database-to-ontology mapping generation for semantic interoperability."},
        {"id":"70","name":"A refinement operator based learning algorithm for the ALC description logic"},
        {"id":"71","name":"A semi-automatic ontology acquisition method for the semantic web"},
        {"id":"72","name":"A geo-temporal web gazetteer integrating data from multiple sources"},
        {"id":"73","name":"Translating sql applications to the semantic web"},
        {"id":"74","name":"Silk-a-link discovery framework for the web of data"},
        {"id":"75","name":"OSMonto - An Ontology of OpenStreetMap Tags"},
        {"id":"76","name":"The Manchester OWL Syntax"},
        {"id":"77","name":"Chinese Whispers and Connected Alignments"},
        {"id":"78","name":"Improving Search and Navigation by Combining Ontologies and Social Tags"},
        {"id":"79","name":"DO-ROAM: Activity-Oriented Search and Navigation with OpenStreetMap"},
        {"id":"80","name":"Spatial Relations for Semantic Similarity Measurement"},
        {"id":"81","name":"The Analysis of Proximities: Multidimensional Scaling with an Unknown Distance Function"},
        {"id":"82","name":"Similarity scaling and cognitive process models"},
        {"id":"83","name":"Concerning the Applicability of Geometric Models to Similarity Data: The Interrelationship Between Similarity and Spatial Density"},
        {"id":"84","name":"Modelling Asymmetric Similarity with Prominence"},
        {"id":"85","name":"Features of Similarity"},
        {"id":"86","name":"Determining Semantic Similarity Among Entity Classes from Different Ontologies"},
        {"id":"87","name":"Development and application of a metric on semantic nets"},
        {"id":"88","name":"Similarity Interactive Activation and Mapping"},
        {"id":"89","name":"Formalizing Conceptual Spaces in Formal Ontology in Information Systems"},
        {"id":"90","name":"Statistik für Sozialwissenschaftler"},
        {"id":"91","name":"Semantic Neighbourhoods for Spatial Relations (Extended Abstract)"},
        {"id":"92","name":"GIS and Multicriteria Decision Analysis"},
        {"id":"93","name":"Geometric Models of Similarity"},
        {"id":"94","name":"Principles of Categorization in Cognition and Categorization"},
        {"id":"95","name":"Statistics - The Exploration and Analysis of Data"},
        {"id":"96","name":"Concepts and Categorization in Comprehensive Handbook of Psychology"},
        {"id":"97","name":"Measuring Semantic Similarity between Geospatial Conceptual Regions"},
        {"id":"98","name":"Conceptual Spaces: The Geometry of Thought"},
        {"id":"99","name":"Cognitive Semantics"},
        {"id":"100","name":"Point-Set Topological Spatial Relations"},
        {"id":"101","name":"Relative Representation of Spatial Knowledge: The 2-C Case"},
        {"id":"102","name":"Using Information Orientation for Qualitative Spatial Reasoning  in Theories and Methods of Spatio-Temporal Reasoning in Geographic Space"},
        {"id":"103","name":"Naive Geography in Spatial Information Theory - A Theoretical Basis for GIS"},

    ],
    "links":[
        {"source":1,"target":2},
        {"source":1,"target":3},
        {"source":1,"target":4},
        {"source":1,"target":5},
        {"source":1,"target":6},
        {"source":1,"target":7},
        {"source":1,"target":8},
        {"source":1,"target":9},
        {"source":1,"target":10},
        {"source":1,"target":11},
        {"source":1,"target":12},
        {"source":1,"target":13},
        {"source":1,"target":14},
        {"source":1,"target":15},
        {"source":1,"target":16},
        {"source":1,"target":17},
        {"source":1,"target":18},
        {"source":1,"target":19},
        {"source":1,"target":20},
        {"source":1,"target":21},
        {"source":1,"target":22},
        {"source":1,"target":23},
        {"source":1,"target":24},
        {"source":1,"target":25},
        {"source":1,"target":26},
        {"source":1,"target":27},
        {"source":1,"target":28},
        {"source":1,"target":29},
        {"source":1,"target":30},
        {"source":1,"target":31},
        {"source":1,"target":32},
        {"source":1,"target":33},
        {"source":1,"target":34},
        {"source":1,"target":35},
        {"source":1,"target":36},
        {"source":1,"target":37},
        {"source":1,"target":38},
        {"source":1,"target":39},
        {"source":1,"target":40},
        {"source":1,"target":41},
        {"source":1,"target":42},
        {"source":1,"target":43},
        {"source":1,"target":44},
        {"source":1,"target":45},
        {"source":1,"target":46},
        {"source":1,"target":47},
        {"source":1,"target":48},
        {"source":1,"target":49},
        {"source":1,"target":50},
        {"source":1,"target":51},
        {"source":1,"target":52},
        {"source":1,"target":53},
        {"source":1,"target":54},
        {"source":1,"target":55},
        {"source":1,"target":56},
        {"source":1,"target":57},
        {"source":1,"target":58},
        {"source":1,"target":59},
        {"source":1,"target":60},
        {"source":1,"target":61},
        {"source":1,"target":62},
        {"source":1,"target":63},
        {"source":6,"target":64},
        {"source":6,"target":65},
        {"source":6,"target":66},
        {"source":6,"target":67},
        {"source":6,"target":68},
        {"source":6,"target":69},
        {"source":6,"target":70},
        {"source":6,"target":71},
        {"source":6,"target":72},
        {"source":6,"target":73},
        {"source":6,"target":74},
        {"source":75,"target":76},
        {"source":75,"target":77},
        {"source":75,"target":78},
        {"source":75,"target":79},
        {"source":80,"target":81},
        {"source":80,"target":82},
        {"source":80,"target":83},
        {"source":80,"target":84},
        {"source":80,"target":85},
        {"source":80,"target":86},
        {"source":80,"target":87},
        {"source":80,"target":88},
        {"source":80,"target":89},
        {"source":80,"target":90},
        {"source":80,"target":91},
        {"source":80,"target":92},
        {"source":80,"target":93},
        {"source":80,"target":94},
        {"source":80,"target":95},
        {"source":80,"target":96},
        {"source":80,"target":97},
        {"source":80,"target":98},
        {"source":80,"target":99},
        {"source":80,"target":100},
        {"source":80,"target":101},
        {"source":80,"target":102},
        {"source":80,"target":103},
        {"source":80,"target":51},
    ],
};