var data = {
    "nodes":[
		{"id":"1","name":"Geographic knowledge extraction and semantic similarity in OpenStreetMap"},
		{"id":"2","name":"Discovering missing links in Wikipedia"},
		{"id":"3","name":"Astudy on similarity and relatedness using distributional andWordnet-based approaches"},
		{"id":"4","name":"Statistics in medicine: calculating confidence intervals for regression and correlation"},
		{"id":"5","name":"Applications of citation-based automatic classification"},
		{"id":"6","name":"LinkedGeoData: adding a spatial dimension to the web of data"},
		{"id":"7","name":"Semantically enriching VGI in support of implicit feedback analysis"},
		{"id":"8","name":"A survey of volunteered open geo-knowledge bases in the semantic web"},
		{"id":"9","name":"Graph structure in the web"},
		{"id":"10","name":"A spreading-activation theory of semantic processing"},
		{"id":"11","name":"A primer on meta-analysis of correlation coefficients: the relationship between patient-reported therapeutic alliance and adult attachment style as an illustration"},
		{"id":"12","name":"Ontological bridge building—using ontologies to merge spatial datasets"},
		{"id":"13","name":"Toward the semantic geospatial web"},
		{"id":"14","name":"An overview of FIPS 173  the spatial data transfer standard."},
		{"id":"15","name":"Meta-analysis of correlation coefficients: A monte carlo comparison of fixed- and random effects methods"},
		{"id":"16","name":"Content based similarity of geographic classes organized as partition hierarchies"},
		{"id":"17","name":"Towards ubiquitous cartography"},
		{"id":"18","name":"GeoWordNet: a resource for geo-spatial applications"},
		{"id":"19","name":"Citizens as sensors: the world of volunteered geography"},
		{"id":"20","name":"How good is volunteered geographical information? A comparative study of Open- StreetMap and ordnance survey datasets"},
		{"id":"21","name":"Web mapping 2"},
		{"id":"22","name":"OpenStreetMap: user-generated street maps"},
		{"id":"23","name":"The complex dynamics of collaborative tagging"},
		{"id":"24","name":"WiKi’mantics: interpreting ontologies with Wikipedia"},
		{"id":"25","name":"Methods of meta-analysis: correcting error and bias in research findings"},
		{"id":"26","name":"A study on the cognitive plausibility of SIM-DL similarity rankings for geographic feature types"},
		{"id":"27","name":"Algorithm"},
		{"id":"28","name":"The semantics of similarity in geographic information retrieval  implementation and application of the SIM-DL similarity server."},
		{"id":"29","name":"Semantic similarity measurement and geospatial applications"},
		{"id":"30","name":"SimRank: a measure of structural-context similarity"},
		{"id":"31","name":"What is the difference? A cognitive dissimilarity measure for information retrieval result sets"},
		{"id":"32","name":"Bibliographic coupling between scientific papers"},
		{"id":"33","name":"Geospatial semantics: why"},
		{"id":"34","name":"Fast single-pair SimRank computation"},
		{"id":"35","name":"A qualitative enquiry into OpenStreetMap making"},
		{"id":"36","name":"MatchSim: a novel similarity measure based on maximum neighborhood matching"},
		{"id":"37","name":"On efficient distance-based similarity search"},
		{"id":"38","name":"Accuracy estimate and optimization techniques for SimRank computation"},
		{"id":"39","name":"Ontologies are us: a unifiedmodel of social networks and semantics"},
		{"id":"40","name":"WordNet: a lexical database for English"},
		{"id":"41","name":"Contextual correlates of semantic similarity"},
		{"id":"42","name":"Ranking the linked data: the case ofDBpedia"},
		{"id":"43","name":"Characteristics of heavily edited objects in OpenStreetMap"},
		{"id":"44","name":"Towards quality metrics forOpenStreetMap"},
		{"id":"45","name":"Analyzing the spatial-semantic interaction of points of interest in volunteered geographic information"},
		{"id":"46","name":"Wikipedia link structure and text mining for semantic relation extraction  Towards a huge scale globalweb ontology"},
		{"id":"47","name":"OpenStreetMap’s growth accelerates"},
		{"id":"48","name":"The computational Geowiki: what why and how"},
		{"id":"49","name":"Using information content to evaluate semantic similarity in a taxonomy"},
		{"id":"50","name":"Emergence of consensus and shared vocabularies in collaborative tagging systems"},
		{"id":"51","name":"Comparing geospatial entity classes: an asymmetric and contextdependent similarity measure"},
		{"id":"52","name":"Contextual correlates of synonymy"},
		{"id":"53","name":"Approaches to semantic similarity measurement for geo-spatial data: a survey"},
		{"id":"54","name":"On similarity measures for multimedia database applications"},
		{"id":"55","name":"Co-citation in the scientific literature: a new measure of the relationship between two documents"},
		{"id":"56","name":"Principles of semantic networks: explorations in the representation of knowledge"},
		{"id":"57","name":"The proof and measurement of association between two things"},
		{"id":"58","name":"The wikification of GIS and its consequences: or Angelina Jolie’s new tattoo and the future of GIS"},
		{"id":"59","name":"Semantic relatedness metric forWikipedia concepts based on link analysis and its application to word sense disambiguation"},
		{"id":"60","name":"Introduction to neogeography"},
		{"id":"61","name":"Beyond topical similarity: a structural similarity measure for retrieving highly similar documents"},
		{"id":"62","name":"Philosophical investigations"},
		{"id":"63","name":"P-Rank: a comprehensive structural similarity measure over information networks"},
    ],
    "links":[
        {"source":1,"target":2},
        {"source":1,"target":3},
        {"source":1,"target":4},
        {"source":1,"target":5},
        {"source":1,"target":6},
        {"source":1,"target":7},
        {"source":1,"target":8},
        {"source":1,"target":9},
        {"source":1,"target":10},
        {"source":1,"target":11},
        {"source":1,"target":12},
        {"source":1,"target":13},
        {"source":1,"target":14},
        {"source":1,"target":15},
        {"source":1,"target":16},
        {"source":1,"target":17},
        {"source":1,"target":18},
        {"source":1,"target":19},
        {"source":1,"target":20},
        {"source":1,"target":21},
        {"source":1,"target":22},
        {"source":1,"target":23},
        {"source":1,"target":24},
        {"source":1,"target":25},
        {"source":1,"target":26},
        {"source":1,"target":27},
        {"source":1,"target":28},
        {"source":1,"target":29},
        {"source":1,"target":30},
        {"source":1,"target":31},
        {"source":1,"target":32},
        {"source":1,"target":33},
        {"source":1,"target":34},
        {"source":1,"target":35},
        {"source":1,"target":36},
        {"source":1,"target":37},
        {"source":1,"target":38},
        {"source":1,"target":39},
        {"source":1,"target":40},
        {"source":1,"target":41},
        {"source":1,"target":42},
        {"source":1,"target":43},
        {"source":1,"target":44},
        {"source":1,"target":45},
        {"source":1,"target":46},
        {"source":1,"target":47},
        {"source":1,"target":48},
        {"source":1,"target":49},
        {"source":1,"target":50},
        {"source":1,"target":51},
        {"source":1,"target":52},
        {"source":1,"target":53},
        {"source":1,"target":54},
        {"source":1,"target":55},
        {"source":1,"target":56},
        {"source":1,"target":57},
        {"source":1,"target":58},
        {"source":1,"target":59},
        {"source":1,"target":60},
        {"source":1,"target":61},
        {"source":1,"target":62},
        {"source":1,"target":63},
    ],
};